language: node_js
node_js: 10
cache:
  directories:
    - node_modules
script: npm start
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  on:
    branch: master
